# Apply to all files without committing:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
# format markdown files
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v2.7.1"
  hooks:
    - id: prettier
      types: [markdown]
      args: ["--prose-wrap", "always", "--print-width", "100"]

# Autofix coding style
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      args: [--config=pyproject.toml]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: "v0.0.249"
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]